//user actions

export const FETCH_USER_STARTED = "FETCH_USER_STARTED";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";

//buzz actions

export const POST_BUZZ_SUCCESS = "POST_BUZZ_SUCCESS";
export const POST_BUZZ_STARTED = "POST_BUZZ_STARTED";
export const POST_BUZZ_FAILED = "POST_BUZZ_FAILED";

export const UPDATE_BUZZ_STARTED = "UPDATE_BUZZ_STARTED";
export const UPDATE_BUZZ_SUCCESS = "UPDATE_BUZZ_SUCCESS";
export const UPDATE_BUZZ_FAILED = "UPDATE_BUZZ_FAILED";

export const DELETE_BUZZ_STARTED = "DELETE_BUZZ_STARTED";
export const DELETE_BUZZ_SUCCESS = "DELETE_BUZZ_SUCCESS";
export const DELETE_BUZZ_FAILED = "DELETE_BUZZ_FAILED";

export const GET_BUZZ_STARTED = "GET_BUZZ_STARTED";
export const GET_BUZZ_SUCCESS = "GET_BUZZ_SUCCESS";
export const GET_BUZZ_FAILED = "GET_BUZZ_FAILED";

export const COMMENT_BUZZ_SUCCESS = "COMMENT_BUZZ_SUCCESS";
export const COMMENT_BUZZ_STARTED = "COMMENT_BUZZ_STARTED";
export const COMMENT_BUZZ_FAILED = "COMMENT_BUZZ_FAILED";

export const UPDATE_COMMENT_STARTED = "UPDATE_COMMENT_STARTED";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILED = "UPDATE_COMMENT_FAILED";

export const REACT_BUZZ_SUCCESS = "REACT_BUZZ_SUCESS";
export const REACT_BUZZ_STARTED = "REACT_BUZZ_STARTED";
export const REACT_BUZZ_FAILED = "REACT_BUZZ_FAILED";

export const UNREACT_BUZZ_SUCCESS = "UNREACT_BUZZ_SUCESS";
export const UNREACT_BUZZ_STARTED = "UNREACT_BUZZ_STARTED";
export const UNREACT_BUZZ_FAILED = "UNREACT_BUZZ_FAILED";
